allign left and exit on error

diff --git a/buildme b/buildme
--- a/buildme
+++ b/buildme
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -e #exit on error
+
 export old="$(pwd)"
 
 rm -rf build
